name: Python Lint
on: 
  push:
      branches:
            main
jobs:
    lint:
        name: python code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set python
              uses: actions/setup-python@v2
              with:
                python-version: 3.x
            - name: Install dependencies
              run: pip install flake8
            - name: Run Flake8
              run: flake8
            
        
        
